-- 1. Enable the spatial "map-math" tools
CREATE EXTENSION IF NOT EXISTS postgis;

-- 2. Create the 'courts' table
CREATE TABLE courts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  -- The app stores standard GeoJSON here: {"type":"Point","coordinates":[lng,lat]}.
  location JSONB NOT NULL,
  address TEXT,
  added_by TEXT DEFAULT (auth.jwt() ->> 'email'),
  status TEXT DEFAULT 'Empty',
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. Create the 'sessions' table
CREATE TABLE sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  court_id BIGINT REFERENCES courts(id),
  user_id UUID DEFAULT auth.uid(),
  check_in_time TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 4. Create an index for GeoJSON location documents
CREATE INDEX courts_location_idx ON courts USING GIN (location);

-- 5. Enable Row Level Security (RLS)
ALTER TABLE courts ENABLE ROW LEVEL SECURITY;
ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;

-- 6. Define Security Policies
-- Everyone can view the court list
CREATE POLICY "Anyone can view courts" ON courts 
  FOR SELECT USING (true);

-- Authenticated users can insert their own check-ins
CREATE POLICY "Users can insert their own check-ins" ON sessions 
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Authenticated users can add a court. The database records the email from
-- their authenticated Supabase token as the court contributor.
CREATE POLICY "Authenticated users can add courts" ON courts
  FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);

-- Optional user-saved courts, used by the Profile page
CREATE TABLE favourite_courts (
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  court_id BIGINT NOT NULL REFERENCES courts(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  PRIMARY KEY (user_id, court_id)
);

ALTER TABLE favourite_courts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users manage their own favourite courts" ON favourite_courts
  FOR ALL TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);
