-- 1. Enable the spatial "map-math" tools
CREATE EXTENSION IF NOT EXISTS postgis;

-- 2. Create the 'courts' table
CREATE TABLE courts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  location GEOGRAPHY(POINT) NOT NULL,
  status TEXT DEFAULT 'Empty',
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. Create the 'sessions' table
CREATE TABLE sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  court_id BIGINT REFERENCES courts(id),
  user_id UUID DEFAULT auth.uid(),
  check_in_time TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 4. Create a spatial index for fast proximity searching
CREATE INDEX courts_location_idx ON courts USING GIST (location);

-- 5. Enable Row Level Security (RLS)
ALTER TABLE courts ENABLE ROW LEVEL SECURITY;
ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;

-- 6. Define Security Policies
-- Everyone can view the court list
CREATE POLICY "Anyone can view courts" ON courts 
  FOR SELECT USING (true);

-- Authenticated users can insert their own check-ins
CREATE POLICY "Users can insert their own check-ins" ON sessions 
  FOR INSERT WITH CHECK (auth.uid() = user_id);